name: intransporia
description: Fun Along The Way.
publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_svg: ^1.1.4
  get_it: ^7.2.0
  hive_flutter: ^1.1.0
  package_info_plus: ^1.4.3+1
  pin_code_fields: ^7.4.0

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/ic_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/main_menu/
    - assets/icons/belanjain/
    - assets/images/logos/
    - assets/images/walktrough/
    - assets/images/banners/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
